### ISSUE TITLE
<Android version 9 > <Device code name RMX 1921> Bootloop on animation

### ISSUE THREAD

**Issue by nandha-2point0** [erfanoabdi/ErfanGSIs#101]
@**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
Add logs to help your problem.
Log file: /data/local/tmp/logs/log
(Bug reports without logs will be rejected)

**Smartphone (please complete the following information):**
 - Device: [e.g. Tissot]
 - Vendor: [e.g. Lineage 16]
 - Version [e.g. Pie]

**Additional context**

**Comment by nandha-2point0** [comment]
Device: rmx1921
Vendor: stock
Version :9

**Comment by 4PERTURE** [comment]
@nandha-2point0 Great description
