### ISSUE TITLE
<Android 10> <oneplus3> [New Pixel GSI A/B roms not boot]

### ISSUE THREAD

**Issue by lufog** [erfanoabdi/ErfanGSIs#102]
**Describe the bug**
All Pixel A/B 10 GSIs that older than **20190926** stuck on "POWERED BY ANDROID"

**To Reproduce**
1. Flash latest **Pixel-AB-10-20191107-ErfanGSI.img**
2. Reboot phone
4. Stuck on "1+ POWERED BY ANDROID" screen

**Expected behavior**
Normal boot

**Logs**
Log file: [log.zip](https://github.com/erfanoabdi/ErfanGSIs/files/3844590/log.zip)
Log file 2: [log.zip](https://github.com/erfanoabdi/ErfanGSIs/files/3844641/log.zip) (the second attempt to boot the OS, with a long wait)

**Smartphone:**
 - Device: OnePlus 3T
 - Vendor: [LineageOS 16.0 Treble (system-as-root)](https://forum.xda-developers.com/oneplus-3/oneplus-3--3t-cross-device-development/treble-lineageos-15-1-treble-oneplus-3-t3830455)
 - Version LineageOS Pie, GSI Android 10

**Additional context**
Pixel A/B 10 GSIs **20190904** and **20190926** are works, they are buggy but works.

**Comment by zainarbani** [comment]
F linker  : CANNOT LINK EXECUTABLE "/vendor/bin/hw/android.hardware.audio@2.0-service": library "libqinder.so" not found

haxed module ??

**Comment by erfanoabdi** [comment]
fix merged https://github.com/erfanoabdi/ErfanGSIs/commit/71432169c867e35f67991562acbde800fa844182
