### ISSUE TITLE
Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by GTAGAME** [erfanoabdi/ErfanGSIs#103]
Status Legend:
(OK):download completed.
Create Temp and out dir
Extracting firmware on: /home/gravarty/ErfanGSIs/working
AB OTA detected
Create Temp dir
Making copy of source rom to temp
Resigning to AOSP keys
Patching started...
Start Patching Light Services for Brightness Fix...
ERR: Patching Light not supported for this rom
Creating Image: Pixel-AB-9-20191123-ErfanGSI.img
/home/gravarty/ErfanGSIs/scripts/../tools/Linux/bin/make_ext4fs: 1: /home/gravarty/ErfanGSIs/scripts/../tools/Linux/bin/make_ext4fs: Syntax error: "(" unexpected
Remove Temp dir
Porting Pixel GSI done on: /home/gravarty/ErfanGSIs/output

EDIT: fixed it by switching to a different distro.. Had problems with it on Xubuntu.
It works fine on Ubuntu.

**Comment by MacTavishAO** [comment]
Closed.
