### ISSUE TITLE
Android 9 <montana> [Bootloop on animation] - Latest OxygenOS

### ISSUE THREAD

**Issue by JarlPenguin** [erfanoabdi/ErfanGSIs#11]
**Describe the bug**
The OxygenOS GSI bootloops.

**To Reproduce**
1. Install LineageOS 16  (Treble)
2. Format system and install OOS GSI.
3. Reboot

**Expected behavior**
The GSI boots properly.

**Screenshots**
N/A

**Logs**
Add logs to help your problem.
Log file: https://del.dog/uvopiyibug.pl

**Smartphone (please complete the following information):**
 - Device: montana
 - Vendor: LineageOS 16.0
 - Version Pie

**Additional context**

**Comment by erfanoabdi** [comment]
remove com.qualcomm.location.xml form your system/etc/permissions or vendor/etc/permissions
that xml shouldn't be on vendor anyway

**Comment by JarlPenguin** [comment]
Doing that fixed it
