### ISSUE TITLE
<Pie> <Mido> Gsi building no such file/dir errors

### ISSUE THREAD

**Issue by hjyoung1** [erfanoabdi/ErfanGSIs#12]
**Describe the bug**
Building oxygen os gsi gives bunch of  "no such file or directory found errors"
Even after errors gsi build was successful but there's problem with booting. 

**To Reproduce**

Followed Readme.md file using ./url2GSI *op6 firmware link here* OxygenOS 

**Screenshots**

![Screenshot_20190613-203825__01__01](https://user-images.githubusercontent.com/45882061/59461041-18668800-8e3e-11e9-8c4e-2240476300b3.jpg)

**Logs**
[log.txt](https://github.com/erfanoabdi/ErfanGSIs/files/3287833/log.txt)

**Smartphone (please complete the following information):**
 - Device: Mido
 - Vendor: Revenge OS v4, v7, los16 
 - Version: Pie

**Additional context**

Gsi boots for 1 sec then reboot again. Endless loop. 
Also above listed vendors boot op7pro gsi perfectly. And other gsis too.

**Comment by MacTavishAO** [comment]
Hey, seems like the problem is `#00 pc 00000000000dcc4c  /system/lib64/libsurfaceflinger.so (android::ExBufferLayer::isHDRLayer() const+48)` if you can give me system/lib64/libsurfaceflinger from op6 i can fix this.

**Comment by hjyoung1** [comment]
Thanks you already fixed that on telegram xD boots fine now. Only round corners bug now but that's not related here. So closing this, Thanks.

**Comment by NZXT03** [comment]
That's OK. Just install gawk.
