### ISSUE TITLE
<Android > <beryllium> [Bug name Ex. Bootloop on animation]

### ISSUE THREAD

**Issue by DeckardShaw** [erfanoabdi/ErfanGSIs#14]
**Describe the bug**
Stuck At bootlogo 

**Logs**
Add logs to help your problem.
Log file: https://pastebin.com/se3b2kvs

**Smartphone (please complete the following information):**
 - Device: [Poco F1]
 - Vendor: beryllium-9.6.10-9.0
 - Version-pie

**Additional context**
logs says drmlibfs: error: invalid config file

**Comment by erfanoabdi** [comment]
send correct logs, not recovery log
