### ISSUE TITLE
OneUi

### ISSUE THREAD

**Issue by RajeshGurijala** [erfanoabdi/ErfanGSIs#142]
### **_When I am Trying To Install GSI OneUi Rom In My Mobile it is showing size of image is larger than target device...._**

**Comment by yukosky** [comment]
The Erfan tool is not to blame if your device does not support the size of the GSI, and this issue is useless (without wanting to be arrogant or similar), search Telegram for your device group or related tutorials on YouTube or similar. Close your Issue dude xd

**Comment by MacTavishAO** [comment]
https://sourceforge.net/projects/mactavishao-builds/files/GSI/OneUI/oneui-0.2.7z/download at least 2.6GB system size required.
