### ISSUE TITLE
<Android Q dev preview> <Nokia 7 plus / B2N> [Bootloop]

### ISSUE THREAD

**Issue by kcetin20** [erfanoabdi/ErfanGSIs#20]
Bootloop on Nokia 7 plus with fresh install waited for 10mins and tried to fix it.

[console-ramoops.zip](https://github.com/erfanoabdi/ErfanGSIs/files/3336000/console-ramoops.zip)

**Comment by erfanoabdi** [comment]
send me /data/local/tmp/logs/log

**Comment by kcetin20** [comment]
> send me /data/local/tmp/logs/log

File is missing in data/local,

i only have ramoops files

**Comment by MacTavishAO** [comment]
Without logcat we're tied down.
