### ISSUE TITLE
<Android 9 Pie> <Vince> [Screen Recorder Not Working]

### ISSUE THREAD

**Issue by oyiramname** [erfanoabdi/ErfanGSIs#22]
**Screen Recorder Not Working**
Screen Recorder Automatically disepear/closed when after touch Record Button.

**Screenshots**
![Screenshot_20190629-071726__01](https://user-images.githubusercontent.com/52336278/60377292-abf3a780-9a3f-11e9-8970-8d79f6e635e3.jpg)

**Logs**
[Log]([Log](https://drive.google.com/file/d/1INQCwRfEVtNJaGx9ogH2uUQHSjiqKBs6/view?usp=drivesdk) 

**Smartphone 
 - Device : Redmi 5 Plus A.k.a Vince
 - Vendor : Serein OS Pie (AOSP)
 - Version : Pie

**Additional context**
Please @erfanoabdi Fix Screen Recorder Issue. Please... please... please...

Telegram : @oyiramname

**Comment by oyiramname** [comment]
This is on OxygenOS A Only 9 20190629 ErfanGSI

**Comment by MacTavishAO** [comment]
This issue is has been dead for couple of months. Use another screen recorder. Closed.
