### ISSUE TITLE
<OxygenOS-AB-9-20190629-ErfanGSI> <Nokia 7 Plus / B2N > [Bootloop on androidone logo / device restarting.]

### ISSUE THREAD

**Issue by kcetin20** [erfanoabdi/ErfanGSIs#23]
Flashed like this 

1. wiped all 
2. install img as system img
3. install permissiverv4
4. reboot.

[console-ramoops.zip](https://github.com/erfanoabdi/ErfanGSIs/files/3341657/console-ramoops.zip)

EDIT : /data/local/tmp/logs/log is empty
/sys/fs/pstore i have only console-ramoops nothing more.

**Comment by MacTavishAO** [comment]
Without logcat we're tied down.
