### ISSUE TITLE
/home/parallels/ErfanGSIs/scripts/mkimage.sh: line 94: 26065 Floating point exceptionsudo $make_ext4fs -T 0 -S $fcontexts -l $syssize -L / -a / -s "$output" "$systemdir/" Remove Temp dir

### ISSUE THREAD

**Issue by hpxing** [erfanoabdi/ErfanGSIs#28]
**Describe the bug**
when i build gsi it is said /home/parallels/ErfanGSIs/scripts/mkimage.sh: line 94: 26065 Floating point exceptionsudo $make_ext4fs -T 0 -S $fcontexts -l $syssize -L / -a / -s "$output" "$systemdir/"
Remove Temp dir

if it manualy set the syssize the script works ok

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
Add logs to help your problem.
Log file: /data/local/tmp/logs/log
(Bug reports without logs will be rejected)

**Smartphone (please complete the following information):**
 - Device: [e.g. Tissot]
 - Vendor: [e.g. Lineage 16]
 - Version [e.g. Pie]

**Additional context**

**Comment by hpxing** [comment]
# Getting system size and add approximately 5% on it just for free space
systemsize=`du -sk $systemdir | awk '{$1*=1024;$1=int($1*1.05);printf("%d\n",$1)}'`
echo $1 $systemsize


this works

**Comment by balliboxer** [comment]
@hpxing To solve this issue just type in cmd
1 = Mkdir out
2 = mkimage.sh systemmount OxygenOS AA out
U have to guide the mkimage.sh to out folder at end

**Comment by hpxing** [comment]
> @hpxing To solve this issue just type in cmd
> 1 = Mkdir out
> 2 = mkimage.sh systemmount OxygenOS AA out
> U have to guide the mkimage.sh to out folder at end
not this reason》 because the syssize is Scientific Counting  like 11111e5
the  $make_ext4fs  accept number like 123444555 integer
