### ISSUE TITLE
<9.0> <violet> [Bootloop on animation] - Flyme

### ISSUE THREAD

**Issue by DiseR-LawnX** [erfanoabdi/ErfanGSIs#36]
**Describe the bug**
My device is stuck in the boot animation

**To Reproduce**
1. Go to 'recovery',clean all data
2. flash pe vendor,then flash gsi and permissiver
3. reboot

**Expected behavior**
boot successfully

**Screenshots**

**Logs**
Add logs to help your problem.
Log file: /data/local/tmp/logs/log
[logcat.log](https://github.com/erfanoabdi/ErfanGSIs/files/3414201/logcat.log)
(Bug reports without logs will be rejected)

**Smartphone (please complete the following information):**
 - Device: [violet]
 - Vendor: [PE CAF]
 - Version [Pie
]

**Additional context**

**Comment by rsyhan** [comment]
![image](https://user-images.githubusercontent.com/30499527/61586376-fbdc0f00-aba4-11e9-883a-127d311df810.png)
I guess you are getting recovery log

Try to get system log from here : /data/local/tmp/logs/log

**Comment by DiseR-LawnX** [comment]
I have to generated new logs
[recovery[1].log](https://github.com/erfanoabdi/ErfanGSIs/files/3414209/recovery.1.log)
[logcat[1].log](https://github.com/erfanoabdi/ErfanGSIs/files/3414210/logcat.1.log)

**Comment by rsyhan** [comment]
> I have to generated new logs
> [recovery[1].log](https://github.com/erfanoabdi/ErfanGSIs/files/3414209/recovery.1.log)
> [logcat[1].log](https://github.com/erfanoabdi/ErfanGSIs/files/3414210/logcat.1.log)

Both are recovery log again.....Why not follow the file I had told you?

**Comment by DiseR-LawnX** [comment]
原来是国人吗,才发现
我/data/local/tmp/logs/log这个目录下没有文件啊

**Comment by DiseR-LawnX** [comment]
我是用的rec生成的log
包括
![image](https://user-images.githubusercontent.com/35911521/61586430-896c2e80-aba6-11e9-95d9-c25785505c29.png)
这几个文件
