### ISSUE TITLE
<Anjadroid ersion> <Device code name> [Bug name Ex. Bootloop on animation]

### ISSUE THREAD

**Issue by Soka20p** [erfanoabdi/ErfanGSIs#40]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
Add logs to help your problem.
Log file: /data/local/tmp/logs/log
(Bug reports without logs will be rejected)

**Smartphone (please complete the following information):**
 - Device: [e.g. Tissot]
 - Vendor: [e.g. Lineage 16]
 - Version [e.g. Pie]

**Additional context**

**Comment by MacTavishAO** [comment]
@Soka20p Can't you guys fill the form ?
