### ISSUE TITLE
<9.0> <Tulip> [Bootloop on animation] Oxygen OS

### ISSUE THREAD

**Issue by arturo51236** [erfanoabdi/ErfanGSIs#41]
[log.txt](https://github.com/erfanoabdi/ErfanGSIs/files/3438289/log.1.txt)

**Comment by arturo51236** [comment]
Bootloop on the boot animation.

Steps to reproduce the behavior:

Flash system
Flash Permissiverv4
Flash FixZygotev2
Reboot

Log:
[log.txt](https://github.com/erfanoabdi/ErfanGSIs/files/3438289/log.txt)

Smartphone:

Device: Tulip (Redmi Note 6 Pro)
Vendor: Xiaomi.eu
Version Pie

**Comment by MacTavishAO** [comment]
You must not flash zygotefix on gsis based on android pie.

**Comment by arturo51236** [comment]
Upss... Thanks, I've tried again and now boot but i have a black screen, new log:
[log[1].txt](https://github.com/erfanoabdi/ErfanGSIs/files/3438327/log.1.txt)

**Comment by MacTavishAO** [comment]
Can you wipe data, remove /vendor/overlay and /system/app/treble-overlay-xiaomi-redminote6pro-systemui and try again ?

**Comment by arturo51236** [comment]
/overlay and /treble-overlay-xiaomi-redminote6pro-systemui don't exists...

**Comment by MacTavishAO** [comment]
tap to vendor and system from twrp's mount options.

**Comment by arturo51236** [comment]
/overlay removed, the other still does not appear after mounting system, I tried to restart

**Comment by MacTavishAO** [comment]
okay then wipe and reboot.

**Comment by arturo51236** [comment]
Okey, it boot but i have this error, after touching "ok" i've got a gray screen, if i touch power button it gets a totally black.
![Screenshot_20190711-115623 1](https://user-images.githubusercontent.com/46931507/61996970-ebdb9800-b09a-11e9-8a90-1ba768e0d4f8.jpg)


Here is a new log:
[log[3].txt](https://github.com/erfanoabdi/ErfanGSIs/files/3438362/log.1.txt)
