### ISSUE TITLE
Can't install system ColorOS

### ISSUE THREAD

**Issue by Saiful220** [erfanoabdi/ErfanGSIs#45]
I can't install System Images ColorOS on Redmi 5(Rosy)
how to fix it?
i have log
this log:
https://www38.zippyshare.com/v/qkjTAQyu/file.html

**Comment by erfanoabdi** [comment]
image 'ColorOS-Aonly-9-20190605-ErfanGSI.img' is larger than target device

**Comment by MacTavishAO** [comment]
Image doesn't fit to your system partition. You can try [https://sourceforge.net/projects/mactavishao-builds/files/GSI/ColorOS%206/](this) which fits to 3GB
