### ISSUE TITLE
<ColorOS> <Mido> [Bootloop on animation]

### ISSUE THREAD

**Issue by hsuanhanSU** [erfanoabdi/ErfanGSIs#46]
**Describe the bug**
Bootloop on Animation

**To Reproduce**
1. Flash Treble Rom(Revenge OS)
2. Flash ColorOS GSI system image (0323Aonly)
3. Flash Permissiver V2
4. Reboot system
5. See error

**Expected behavior**
Reboot to system

**Screenshots**

**Logs**
https://www.sendspace.com/file/wjgi3x

**Smartphone (please complete the following information):**
 - Device: Mido
 - Vendor: Revenge OS
 - Version Pie

**Additional context**

**Comment by hsuanhanSU** [comment]
Update:
When I flash newer ColorOS GSI(0605)
It says"Size of image is larger than target device

**Comment by spdroid** [comment]
Multiple thread for same issue. 

"Size of image is larger than target device" - it means the system img is bigger than your device's system size.
