### ISSUE TITLE
<ColorOS> <Mido> [Bootloop on animation]

### ISSUE THREAD

**Issue by hsuanhanSU** [erfanoabdi/ErfanGSIs#47]
Describe the bug
Bootloop on Animation

To Reproduce

Flash Treble Rom(Revenge OS)
Flash ColorOS GSI system image (0323Aonly)
Flash Permissiver V2
Reboot system
See error
Expected behavior
Reboot to system

Screenshots

Logs
https://www.sendspace.com/file/tvl181

Smartphone (please complete the following information):

Device: Mido
Vendor: Revenge OS
Version Pie
Additional context

**Comment by spdroid** [comment]
ColorOS is dead for now and so this issue. 😂
