### ISSUE TITLE
<Android version> <Device code name> [Bug name Ex. Bootloop on animation]

### ISSUE THREAD

**Issue by nikitakurtash** [erfanoabdi/ErfanGSIs#48]
**Describe the bug**
I click on the item, it gives an error

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Screen'
3. Click on 'Always-on Panel'
4. See erro

**Expected behavior**
Always-on Panel on/off

**Screenshots**

![Screenshot_20190809-083414318](https://user-images.githubusercontent.com/53928985/62756465-8b782d80-ba80-11e9-8558-a1f467dba6e6.jpg)
![Screenshot_20190809-083425659](https://user-images.githubusercontent.com/53928985/62756469-90d57800-ba80-11e9-9208-a9232725a4e3.jpg)

**Logs**

[2019-08-09_08.30.zip](https://github.com/erfanoabdi/ErfanGSIs/files/3484891/2019-08-09_08.30.zip)

**Smartphone (please complete the following information):**
 - Device: Lavender
 - Vendor: Lineage 16
 - Version Pie

**Additional context**

**Comment by spdroid** [comment]
Multiple issue thread for same problem.
