### ISSUE TITLE
<ZenUi> <Lavender> [Bug name Ex. Bootloop on animation]

### ISSUE THREAD

**Issue by nikitakurtash** [erfanoabdi/ErfanGSIs#49]
**Describe the bug**
I click on the item, it gives an error

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Screen'
3. Click on 'Always-on Panel'
4. See erro

**Expected behavior**
Always-on Panel on/off

**Screenshots**

![Screenshot_20190809-083414318](https://user-images.githubusercontent.com/53928985/62756465-8b782d80-ba80-11e9-8558-a1f467dba6e6.jpg)
![Screenshot_20190809-083425659](https://user-images.githubusercontent.com/53928985/62756469-90d57800-ba80-11e9-9208-a9232725a4e3.jpg)

**Logs**

[2019-08-09_08.30.zip](https://github.com/erfanoabdi/ErfanGSIs/files/3484891/2019-08-09_08.30.zip)

**Smartphone (please complete the following information):**
 - Device: Lavender
 - Vendor: Lineage 16
 - Version Pie

**Additional context**

**Comment by spdroid** [comment]
In OEM GSIs, not everything works. Some things are exclusive for certain devices and require specific hardware and software just like Ambient display and face lock on One Plus GSIs.  As far as I know, In zenui, AOD is on by default. If you want solution (Want to turn it off totally) , send me the systemUI and framework-res apk from system.
