### ISSUE TITLE
<miui Q MIUI-AB-10-20190813-ErfanGSI> <tissot> [Bug name Ex. Bootloop on animation]

### ISSUE THREAD

**Issue by hpxing** [erfanoabdi/ErfanGSIs#52]
**Describe the bug**
Bootloop on animation] 

[log.zip](https://github.com/erfanoabdi/ErfanGSIs/files/3512305/log.zip)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
Add logs to help your problem.
Log file: /data/local/tmp/logs/log
(Bug reports without logs will be rejected)

**Smartphone (please complete the following information):**
 - Device: [e.g. Tissot]
 - Vendor: [e.g. Lineage 16]
 - Version [e.g. Pie]

**Additional context**

**Comment by erfanoabdi** [comment]
thanks for logs, yeah non pixel Q gsis is still WIP and buggy

**Comment by MacTavishAO** [comment]
@hpxing Can't you just fill the form ?
