### ISSUE TITLE
<any Android q gsi> <X00T> [i have fingerprint.xml in vendor/etc/permissions but not in settings security]

### ISSUE THREAD

**Issue by erkanbey1** [erfanoabdi/ErfanGSIs#54]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
Add logs to help your problem.
Log file: /data/local/tmp/logs/log
(Bug reports without logs will be rejected)

**Smartphone (please complete the following information):**
 - Device: [e.g. Tissot]
 - Vendor: [e.g. Lineage 16]
 - Version [e.g. Pie]

**Additional context**

**Comment by adi8900** [comment]
@erkanbey1 Where logcat?

**Comment by amackpro** [comment]
@erkanbey1 Bad vendor .. as u Using  X00T  I recommend you to use Nitrogen Os latest vendor for base and Latest firmware

**Comment by erkanbey1** [comment]
https://m.youtube.com/watch?v=By6dXXYjPjc i do same things but no fingerprint in settings

**Comment by MacTavishAO** [comment]
Logs are most important thing in our lives.

**Comment by MacTavishAO** [comment]
Lack of information and dead conversation. Closed.
