### ISSUE TITLE
<any Android q gsi> <X00T> [i have fingerprint.xml in vendor/etc/permissions but not in settings security]

### ISSUE THREAD

**Issue by erkanbey1** [erfanoabdi/ErfanGSIs#55]
https://m.youtube.com/watch?v=By6dXXYjPjc i do same things but no fingerprint/pixel imprint in settings

**Comment by amackpro** [comment]
@erkanbey1 Use latest Firmware

**Comment by erkanbey1** [comment]
Not working

18 Ağu 2019 Paz 16:24 tarihinde amackpro <notifications@github.com> şunu
yazdı:

**Comment by erkanbey1** [comment]
İm using 056

19 Ağu 2019 Pzt 12:39 tarihinde ErkanArtz <boydiamond11@gmail.com> şunu
yazdı:

**Comment by spdroid** [comment]
You are just spamming , do what amackpro said. Closing this issue, multiple copy of same issue.
