### ISSUE TITLE
10 vince VoLTE not working

### ISSUE THREAD

**Issue by NinoJoy** [erfanoabdi/ErfanGSIs#56]
VoLTE is not available with JIO sim

Device; Redmi Note 5/5 Plus
Vendor: Beast ROM Pie Vendor
Image: Pixel 10 A-only gsi

**Comment by adi8900** [comment]
@NinoJoy Huh

**Comment by NinoJoy** [comment]
Any fix available?

**Comment by adi8900** [comment]
@NinoJoy No,wait for release source by Google maybr
