### ISSUE TITLE
Android 10 go gsi build

### ISSUE THREAD

**Issue by proganime1200** [erfanoabdi/ErfanGSIs#67]
Help erfanoabdi could you build android 10 go gsi for my redmi go  or for any go devices i have 1.2 gb system image size i cant fit the iamges that you provided

**Comment by JSPiRiT1337** [comment]
@proganime1200 Redmi go is arm device
There is no pixel devices with arm to port from
Btw u can easily debloat gsi to 1.2gb but it wont help you

**Comment by proganime1200** [comment]
> @proganime1200 Android go is just few lines in build.prop
> u want Q arm but there is no devices with Q and arm
> can't you understand this?

nevermind android 10 for arm is being released for test thanks for phhusson
