### ISSUE TITLE
<Pixel GSI, 10, A-only, 28092019> <Santoni (Redmi 4X)> Bootloop on animation after flashing GSI

### ISSUE THREAD

**Issue by TheGreySquare** [erfanoabdi/ErfanGSIs#73]
**Description**
Got a bootloop after flashing recent build. Didn't flash permissiver and fixzygote as mentioned for post 2609 builds.

**Logs**
Adding logs (Several, just in case):
1. Log file: /data/local/tmp/logs/log ([1.zip](https://github.com/erfanoabdi/ErfanGSIs/files/3666358/1.zip)) 
2. All files in: /sys/fs/pstore ([2.zip](https://github.com/erfanoabdi/ErfanGSIs/files/3666359/2.zip))
3. ADB Log (Although, this one appears to be broken, judging by what I saw in .txt, I dunno): adb logcat -d >log.txt ([3.zip](https://github.com/erfanoabdi/ErfanGSIs/files/3666360/3.zip))

(Taken after rebooting into TWRP after bootloop)

**Smartphone (please complete the following information):**
 - Device: Santoni (Redmi 4X)
 - Vendor: dotOS-P-v3.0-santoni-OFFICIAL-20190222-1810
 - Version Vendor: Pie; GSI: 10

**Comment by shivvvvvv** [comment]
Seems like fixed after watching your new issue regarding chrome fc on Pixel GSI. Time to nuke.
