### ISSUE TITLE
MAC install error No available formula with the name "liblzma-dev" 

### ISSUE THREAD

**Issue by hpxing** [erfanoabdi/ErfanGSIs#8]
Brew install protobuf liblzma-dev brotli lz4
Error: No available formula with the name "liblzma-dev" 
lzma is now part of the xz formula:
  brew install xz

should i changed to  Brew install protobuf xz brotli lz4

**Comment by erfanoabdi** [comment]
yep do it plz

**Comment by hpxing** [comment]
Extracting archive: downloads/temp.zip
--
Path = downloads/temp.zip
Type = zip
Physical Size = 2044566177

Everything is Ok 

Size:       3758096384
Compressed: 2044566177
Invalid sparse file format at header magi
Failed to read sparse file
./zip2img.sh: line 200: gawk: command not found

how to solve this?

**Comment by spdroid** [comment]
@hpxing https://github.com/erfanoabdi/ErfanGSIs/issues/8#issuecomment-501247143

**Comment by hpxing** [comment]
mount: You must specify a filesystem type with -t.  
macos can not mount ext4 
i am now using ubuntu to try in vm

**Comment by MacTavishAO** [comment]
> mount: You must specify a filesystem type with -t.
> macos can not mount ext4
> i am now using ubuntu to try in vm

use [fuse-ext2](https://github.com/alperakcan/fuse-ext2)
