### ISSUE TITLE
<Android 10> <X01BD> [Bug name Ex. Bootloop on animation]

### ISSUE THREAD

**Issue by chandupatra** [erfanoabdi/ErfanGSIs#92]
My Zenfone max pro m2 having bootloops after I installed the oxygen os Android 10 10-10-2019 gsi build.. I have done all the pre required steps as needed. #

**To Reproduce**
``

**Logs**
Add logs to help your problem.
Log file: /data/local/tmp/logs/log
(Bug reports without logs will be rejected)

**Smartphone (please complete the following information):**
 - Device: Asus Zenfone max pro m2  X01BD
 - Vendor: [Arrow OS]
 - Version [. Pie]

**Comment by MacTavishAO** [comment]
Missing logs.
