### ISSUE TITLE
<9> <Lithium> [Bootloop to Bootloader]

### ISSUE THREAD

**Issue by serene-code** [erfanoabdi/ErfanGSIs#97]
tried to install the MIUI GSI on Mi Mix, everything goes fine but phone boots to bootloader.
Attached please find the logs.
Log file: 
[android.zip](https://github.com/erfanoabdi/ErfanGSIs/files/3743800/android.zip)

 - Device: Mi Mix (Lithium)
 - Vendor: fw_lithium_miui_MIMIXGlobal_9.6.27_ffd0ee5403_8.0
 - Version: Pie

**Comment by MacTavishAO** [comment]
I see you are using miui as base, but mi mix released with marshmallow. Unless you install GSI over treblized rom you cannot boot it. Btw files inside "android.zip" isn't logs. Closed.
